### ISSUE TITLE
Supporting Solaris 10

### ISSUE THREAD

**Issue by tjyang** [bernd/librrd-ruby#2]
1. Solaris 10 and under has no rrdtool as system file,  I have to modify the the generated Makefile in order to build librrd-1.0.0 against rrdtool 1.2 lib/include under /opt/rrdtool12.

I am looking for way to adjust  ext/librrd/extconf.rb to support this case better.

bash-3.00# diff -u Makefile~ Makefile
--- Makefile~   Wed Jun 15 13:23:17 2011
+++ Makefile    Wed Jun 15 13:33:29 2011
@@ -49,7 +49,7 @@
 DEFS     = -D_FILE_OFFSET_BITS=64
 CPPFLAGS =  -I/opt/rrdtool12/include -I/opt/libedit21/include -I/opt/ncurses56/include -I/opt/ncurses56/include/ncurses -I/opt/libopenssl098/include -I/opt/libz12/include -I/opt/tcl85/include -I/opt/tk85/include  -D_FILE_OFFSET_BITS=64 -I/opt/libedit21/include -I/opt/ncurses56/include -I/opt/ncurses56/include/ncurses -I/opt/libopenssl098/include -I/opt/libz12/include -I/opt/tcl85/include -I/opt/tk85/include
 CXXFLAGS = $(CFLAGS)
-ldflags  = -L. -L/opt/ruby18/lib -L/opt/libedit21/lib -L/opt/ncurses56/lib -L/opt/libopenssl098/lib -L/opt/libz12/lib -L/opt/tcl85/lib -L/opt/tk85/lib -R/opt/ruby18/lib:/opt/libedit21/lib:/opt/ncurses56/lib:/opt/libopenssl098/lib:/opt/libz12/lib:/opt/tcl85/lib:/opt/tk85/lib
+ldflags  = -L. -L/opt/ruby18/lib -L/opt/libedit21/lib -L/opt/ncurses56/lib -L/opt/libopenssl098/lib -L/opt/libz12/lib -L/opt/tcl85/lib -L/opt/tk85/lib -L/opt/rrdtool12/lib -R/opt/ruby18/lib:/opt/libedit21/lib:/opt/ncurses56/lib:/opt/libopenssl098/lib:/opt/libz12/lib:/opt/tcl85/lib:/opt/tk85/lib:/opt/rrdtool12/lib
 dldflags =
 archflag =
 DLDFLAGS = $(dldflags) $(archflag)
bash-3.00#
1. I have to make above change so "librrd.so.2. => ...."  can be found. ie add /opt/rrdtool12/lib into LDFLAGS.
   bash-3.00# ldd RRD.so
       librrd.so.2 =>   /opt/rrdtool12/lib/librrd.so.2
       libpthread.so.1 =>       /lib/libpthread.so.1
       librt.so.1 =>    /lib/librt.so.1
       libdl.so.1 =>    /lib/libdl.so.1
       libcrypt_d.so.1 =>       /usr/lib/libcrypt_d.so.1
       libm.so.2 =>     /lib/libm.so.2
       libc.so.1 =>     /lib/libc.so.1
       libfreetype.so.6 =>      /opt/libttf21/lib/libfreetype.so.6
       libpng.so.2 =>   /opt/libpng12/lib/libpng.so.2
       libz.so.2 =>     /opt/zlib11/lib/libz.so.2
       libart_lgpl_2.so.2 =>    /opt/libart23/lib/libart_lgpl_2.so.2
       libaio.so.1 =>   /lib/libaio.so.1
       libmd.so.1 =>    /lib/libmd.so.1
       libgen.so.1 =>   /lib/libgen.so.1
       /platform/SUNW,SPARC-Enterprise-T5120/lib/libc_psr.so.1
       /platform/SUNW,SPARC-Enterprise-T5120/lib/libmd_psr.so.1
   bash-3.00#
2. Following  change along  won't cut it.  

bash-3.00# grep rrdtool Rakefile
  sh "ruby ext/librrd/extconf.rb --with-rrd-include=/opt/rrdtool12/include --with-rrd-lib=/opt/rrdtool12/lib && make"
bash-3.00#
1. I added following code under OPENBSD in extconf.rb
   
   when /sparc-solaris2.10/i
     puts "On Solaris : #{RUBY_PLATFORM}"
     $LDFLAGS += ' -L/opt/moto/rrdtool12/lib -R/opt/moto/rrdtool12/lib'

But this is also a hack like OpenBSD one.
1. So the question is how can I pass on option to LDFLAGS from "gem  install librrd" ?
   like "gem install librrd --with-rrd-dir=/opt/rrdtool12 LDFLAG=/opt/rrdtool12/lib"

**Comment by bernd** [comment]
Can you check if it works with commit 95e3aea in the solaris10-rrd2 branch?

**Comment by tjyang** [comment]
beside 95e3aea, I also need to make following change in Rakefile to have rake compile and generate the RRD.so.

sh "ruby ext/librrd/extconf.rb --with-rrd-include=/opt/rrdtool12/include --with-rrd-lib=/opt/rrdtool12/lib && make"

But this is really not a good approach since /opt/rrdtool12 is not a standard place in Solaris.
My goal is to be able run following command

gem install librrd --with-rrd-dir=/opt/rrdtool12 LDFLAG=/opt/rrdtool12/lib

I am still new on Rake tool, so I can't help much for now.

**Comment by bernd** [comment]
Ah, okay. I think I understand now. You can do the following. (Note the `--`)

```
gem install librrd -- --with-rrd-dir=/opt/rrdtool12
```

That will add `-I/opt/rrdtool12/include` and `-L/opt/rrdtool12/lib` to the build.

**Comment by tjyang** [comment]
On Tue, Jun 21, 2011 at 6:06 PM, bernd
reply@reply.github.com
wrote:

> Ah, okay. I think I understand now. You can do the following. (Note the `--`)
> 
>    gem install librrd -- --with-rrd-dir=/opt/rrdtool12
> 
> That will add `-I/opt/rrdtool12/include` and `-L/opt/rrdtool12/lib` to the build.

above trick is good but not good enough.
See following librrd.so.2 did'n't bind to /opt/rrdtoool12/lib/librrd.so.2.0.5

bash-3.00# ldd librrd-1.0.0/ext/RRD.so
        librrd.so.2 =>   (file not found)
        libpthread.so.1 =>       /lib/libpthread.so.1
        librt.so.1 =>    /lib/librt.so.1
        libdl.so.1 =>    /lib/libdl.so.1
        libcrypt_d.so.1 =>       /usr/lib/libcrypt_d.so.1
        libm.so.2 =>     /lib/libm.so.2
        libc.so.1 =>     /lib/libc.so.1
        libaio.so.1 =>   /lib/libaio.so.1
        libmd.so.1 =>    /lib/libmd.so.1
        libgen.so.1 =>   /lib/libgen.so.1
        /platform/SUNW,SPARC-Enterprise-T5120/lib/libc_psr.so.1
        /platform/SUNW,SPARC-Enterprise-T5120/lib/libmd_psr.so.1
bash-3.00#

Some where need to be changed so that LDFLAGS can be automatically
added  with "-L/opt/rrdtool12/lib" from
"gem install librrd -- --with-rrd-dir=/opt/rrdtool12" command line.

Thus following patch won't be needed.
- when /solaris/i  
-  puts "Using Solaris hacks"
-  $CPPFLAGS += ' -I/opt/rrdtool12/include'
-  $LDFLAGS += ' -L/opt/rrdtool12/lib'

Thanks for the help so far

tj

> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bernd/librrd-ruby/issues/2#issuecomment-1414599

## 

T.J. Yang

**Comment by bernd** [comment]
Can you please send me the output of the following command.

```
gem install -V librrd -- --with-rrd-dir=/opt/rrdtool12
```

When I do that on my Ubuntu Linux box I get the following.

```
gcc -shared -o RRD.so main.o -L. -L/home/bernd/.rvm/rubies/ruby-1.8.7-p334/lib
  -Wl,-R/home/bernd/.rvm/rubies/ruby-1.8.7-p334/lib -L/opt/rrdtool12/lib -Wl,-R/opt/rrdtool12/lib
  -L.  -rdynamic -Wl,-export-dynamic    -Wl,-R -Wl,/home/bernd/.rvm/rubies/ruby-1.8.7-p334/lib
  -L/home/bernd/.rvm/rubies/ruby-1.8.7-p334/lib -lruby -lrrd  -lrt -ldl -lcrypt -lm   -lc
```

So `-L/opt/rrdtool12/lib` gets added to the command line. As said, this is on Linux. It might be different on Solaris.
I currently don't have access to a Solaris box unfortunately.

**Comment by bernd** [comment]
No response in 5 months. I'll close this ticket, please re-open if the issue is still there.
